# Generated by Django 6.1 on 2026-08-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_images_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="header",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
