# Generated by Django 6.1 on 2026-08-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_header"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="header",
            field=models.ImageField(blank=True, null=True, upload_to="headers"),
        ),
    ]
